server:
  port: 8080

todo:
  auth:
    enabled: true
    api-key: "Password"

spring:
  application:
    name: todo-java

  datasource:
    url: jdbc:h2:mem:todo;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2
